# Generated by Django 4.0.4 on 2022-04-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_site', models.IntegerField(blank=True, null=True)),
                ('station_name', models.CharField(blank=True, max_length=255, null=True)),
                ('station_address', models.CharField(blank=True, max_length=255, null=True)),
                ('station_tank', models.IntegerField(blank=True, null=True)),
                ('station_tel', models.CharField(blank=True, max_length=255, null=True)),
                ('station_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('station_email', models.CharField(blank=True, max_length=255, null=True)),
                ('station_tax_id', models.CharField(blank=True, max_length=255, null=True)),
                ('station_ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('station_port_number', models.CharField(blank=True, max_length=255, null=True)),
                ('station_user', models.CharField(blank=True, max_length=255, null=True)),
                ('station_password', models.CharField(blank=True, max_length=255, null=True)),
                ('station_db_databasename', models.CharField(blank=True, max_length=255, null=True)),
                ('station_line_token', models.CharField(blank=True, max_length=255, null=True)),
                ('station_active', models.BooleanField(default=False)),
                ('line_notify', models.BooleanField(default=False)),
                ('email_notify', models.BooleanField(default=False)),
                ('datetime_modify', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ข้อมูลการตั้งค่าสถานี',
                'verbose_name_plural': 'ตั้งค่าข้อมูลสถานี',
                'ordering': ('station_site',),
            },
        ),
    ]
