# Generated by Django 4.0.4 on 2022-04-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_token', models.TextField(blank=True, null=True)),
                ('line_id', models.CharField(blank=True, max_length=255, null=True)),
                ('line_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime_modify', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ตั้งค่า LineSetting',
                'verbose_name_plural': 'ตั้งค่าข้อมูล LineServer',
                'ordering': ('id',),
            },
        ),
    ]
