# Generated by Django 4.0.4 on 2022-04-22 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_linesetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linesetting',
            old_name='line_comment',
            new_name='line_channelID',
        ),
    ]
