# Generated by Django 4.0.4 on 2022-04-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_line_comment_linesetting_line_channelid'),
    ]

    operations = [
        migrations.AddField(
            model_name='linesetting',
            name='line_destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
