# Generated by Django 4.0.4 on 2022-04-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_linesetting_line_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('user_lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_userid', models.CharField(blank=True, max_length=255, null=True)),
                ('user_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_picture_url', models.URLField()),
                ('user_status_message', models.CharField(blank=True, max_length=255, null=True)),
                ('user_activate', models.BooleanField(default=False)),
                ('user_station_type', models.CharField(blank=True, max_length=255, null=True)),
                ('user_station_level', models.CharField(blank=True, max_length=255, null=True)),
                ('user_notify', models.BooleanField(default=False)),
                ('timestramp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ข้อมูล ติดต่อสำหรับผู้ใช้งานระบบ',
                'verbose_name_plural': 'ข้อมูล ติดต่อสำหรับผู้ใช้งานระบบ',
                'ordering': ('id',),
            },
        ),
    ]
