# Generated by Django 4.0.4 on 2022-04-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_personuser_user_station_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_type', models.CharField(blank=True, max_length=255, null=True)),
                ('position_name', models.CharField(blank=True, max_length=255, null=True)),
                ('timestramp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ข้อมูลตำแหน่งพนักงาน',
                'verbose_name_plural': 'ข้อมูลตำแหน่งพนักงาน',
                'ordering': ('id',),
            },
        ),
    ]
