# Generated by Django 4.0.4 on 2022-04-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_personuser_user_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_type', models.CharField(blank=True, max_length=255, null=True)),
                ('area_name', models.CharField(blank=True, max_length=255, null=True)),
                ('timestramp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ข้อมูลผู้จัดการเขต',
                'verbose_name_plural': 'ข้อมูลผู้จัดการเขต',
                'ordering': ('id',),
            },
        ),
    ]
