# Generated by Django 4.0.4 on 2022-04-23 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='personuser',
            name='user_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.area'),
        ),
    ]
