# Generated by Django 4.0.4 on 2022-04-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_area_area_avaliable_area_area_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='area_avaliable',
            new_name='user_activate',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='area_name',
            new_name='user_display_name',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='area_type',
            new_name='user_status_message',
        ),
        migrations.RemoveField(
            model_name='area',
            name='area_user',
        ),
        migrations.AddField(
            model_name='area',
            name='user_notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='area',
            name='user_picture_url',
            field=models.URLField(default='none'),
        ),
        migrations.AddField(
            model_name='area',
            name='user_userid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
