# Generated by Django 4.0.4 on 2022-04-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_area_avaliable_area_user_activate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linesetting',
            name='rich_main_menu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linesetting',
            name='rich_select_munu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
