# Generated by Django 4.0.4 on 2022-04-27 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_linesetting_rich_main_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='user_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.position'),
        ),
        migrations.AddField(
            model_name='stationprofile',
            name='station_area_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.area'),
        ),
        migrations.AddField(
            model_name='stationprofile',
            name='station_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.personuser'),
        ),
    ]
