# Generated by Django 4.0.4 on 2022-04-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_area_user_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='user_select_area',
            field=models.CharField(choices=[('DieselPremium', 'DieselPremium'), ('DieselB7', 'DieselB7'), ('Diesel', 'Diesel'), ('DieselB20', 'DieselB20'), ('Benzin', 'Benzin'), ('Gasohol95', 'Gasohol95'), ('Gasohol91', 'Gasohol91'), ('GasoholE20', 'GasoholE20'), ('GasoholE85', 'GasoholE85')], default='--', max_length=255),
        ),
    ]
