# Generated by Django 4.0.4 on 2022-04-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_area_user_select_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='user_select_area',
            new_name='product_name',
        ),
    ]
