# Generated by Django 4.0.4 on 2022-05-16 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_areacodetype_area_code_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacodetype',
            name='timestramp',
        ),
        migrations.AddField(
            model_name='areacodetype',
            name='adddatetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areacodetype',
            name='area_register',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='areacodetype',
            name='register_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
