# Generated by Django 4.0.4 on 2022-05-17 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_stationmanagercodetype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationmanagercodetype',
            options={'ordering': ('id',), 'verbose_name': 'ข้อมูล รายละเอียด ID ผู้จัดการสถานี', 'verbose_name_plural': 'ข้อมูล รายละเอียด ID ผู้จัดการสถานี'},
        ),
        migrations.CreateModel(
            name='UserListCodeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userList_name', models.CharField(blank=True, max_length=255, null=True)),
                ('userList_adddatetime', models.DateTimeField(auto_now_add=True)),
                ('userList_register', models.BooleanField(default=False)),
                ('userList_register_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('userList_userid', models.CharField(blank=True, max_length=255, null=True)),
                ('userList_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('userList_picture_url', models.URLField()),
                ('userList_status_message', models.CharField(blank=True, max_length=255, null=True)),
                ('userList_activate', models.BooleanField(default=False)),
                ('userList_notify', models.BooleanField(default=False)),
                ('userList_area_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.areacodetype')),
                ('userList_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.position')),
                ('userList_station_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.stationprofile')),
            ],
            options={
                'verbose_name': 'ข้อมูล รายละเอียด ID ผู้ใช้งานระบบทั้งหมด',
                'verbose_name_plural': 'ข้อมูล รายละเอียด ID ผู้ใช้งานระบบทั้งหมด',
                'ordering': ('id',),
            },
        ),
    ]
