# Generated by Django 4.0.4 on 2022-05-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_stationmanagercodetype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlistcodetype',
            options={'ordering': ('id',), 'verbose_name': 'ข้อมูล ID ผู้ใช้งานระบบ', 'verbose_name_plural': 'ข้อมูล ID ผู้ใช้งานระบบ'},
        ),
        migrations.AlterField(
            model_name='stationprofile',
            name='station_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
