# Generated by Django 4.0.4 on 2022-05-17 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_userlistcodetype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationprofile',
            name='station_area_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.areacodetype'),
        ),
    ]
