# Generated by Django 4.0.4 on 2022-05-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_stationprofile_station_area_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyByRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apporove_new_site_manager', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ตั้งค่าการแจ้งเตือน',
                'verbose_name_plural': 'ตั้งค่าการแจ้งเตือน',
                'ordering': ('id',),
            },
        ),
    ]
