# Generated by Django 4.0.4 on 2022-05-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_notifybyrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifybyrequest',
            old_name='Apporove_new_site_manager',
            new_name='request_approve',
        ),
    ]
