# Generated by Django 4.0.4 on 2022-05-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_rename_request_approve_notifybyrequest_approve_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifybyrequest',
            old_name='approve_type',
            new_name='flex_message_send_to_user',
        ),
        migrations.AddField(
            model_name='notifybyrequest',
            name='line_notify_send_to_group',
            field=models.BooleanField(default=False),
        ),
    ]
