# Generated by Django 4.0.4 on 2022-05-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_rename_approve_type_notifybyrequest_flex_message_send_to_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifybyrequest',
            name='need_admin_approve',
            field=models.BooleanField(default=False),
        ),
    ]
