# Generated by Django 4.0.4 on 2022-05-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_linesetting_line_notify_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlistcodetype',
            name='userList_member_mode',
            field=models.CharField(blank=True, default='register', max_length=255, null=True),
        ),
    ]
