# Generated by Django 4.0.4 on 2022-05-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_userlistcodetype_userlist_member_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlistcodetype',
            name='userList_approved_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
