# Generated by Django 4.0.4 on 2022-05-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_userlistcodetype_userlist_approved_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlistcodetype',
            old_name='userList_adddatetime',
            new_name='userList_add_bot_datetime',
        ),
    ]
