# Generated by Django 4.0.4 on 2022-05-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_rename_userlist_adddatetime_userlistcodetype_userlist_add_bot_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacodetype',
            name='area_display_name',
        ),
        migrations.RemoveField(
            model_name='areacodetype',
            name='area_picture_url',
        ),
        migrations.RemoveField(
            model_name='areacodetype',
            name='area_status_message',
        ),
        migrations.RemoveField(
            model_name='areacodetype',
            name='area_userid',
        ),
    ]
