# Generated by Django 4.0.4 on 2022-05-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_areacodetype_area_display_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacodetype',
            name='area_notify',
        ),
    ]
