# Generated by Django 4.0.4 on 2022-05-19 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_userlistcodetype_userlist_takecare_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiStationTackCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestramp', models.DateTimeField(auto_now_add=True)),
                ('multi_manager_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.userlistcodetype')),
                ('multi_station_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.stationprofile')),
            ],
            options={
                'verbose_name': 'ส่วนดูแลสาขา Multi Station',
                'verbose_name_plural': 'ส่วนดูแลสาขา Multi Station',
                'ordering': ('id',),
            },
        ),
    ]
