# Generated by Django 4.0.4 on 2022-05-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_multistationtackcare'),
    ]

    operations = [
        migrations.AddField(
            model_name='multistationtackcare',
            name='multi_manager_name',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
    ]
