# Generated by Django 4.0.4 on 2022-05-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_rename_multi_manager_id_multistationtackcare_multi_manager_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multistationtackcare',
            name='multi_active',
            field=models.BooleanField(default=False),
        ),
    ]
