# Generated by Django 4.0.4 on 2022-05-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_multistationtackcare_multi_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistationtackcare',
            name='multi_active',
            field=models.BooleanField(default=True),
        ),
    ]
