# Generated by Django 4.0.4 on 2022-05-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_multistationtackcare_multi_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multistationtackcare',
            old_name='timestramp',
            new_name='active_time',
        ),
    ]
