# Generated by Django 4.0.4 on 2022-05-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_rename_timestramp_multistationtackcare_active_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='multistationtackcare',
            name='deactive_ime',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='multistationtackcare',
            name='active_time',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
