# Generated by Django 4.0.4 on 2022-05-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_alter_multistationtackcare_active_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistationtackcare',
            name='deactive_ime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
