# Generated by Django 4.0.4 on 2022-05-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_multistationtackcare_deactive_ime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeInAreaDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_in_area_code_name', models.CharField(blank=True, max_length=255, null=True)),
                ('code_in_area_mamager_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'ข้อมูล รายละเอียดเขตการดูแล',
                'verbose_name_plural': 'ข้อมูล รายละเอียดเขตการดูแล',
                'ordering': ('id',),
            },
        ),
    ]
