# Generated by Django 4.0.4 on 2022-05-21 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_codeinareadetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeinareadetail',
            name='code_in_area_mamager_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.areacodetype'),
        ),
    ]
