# Generated by Django 4.0.4 on 2022-05-21 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_codeinareadetail_code_in_area_mamager_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeinareadetail',
            name='code_in_area_mamager_name',
        ),
    ]
