# Generated by Django 4.0.4 on 2022-05-21 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_alter_areacodetype_area_code_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacodetype',
            name='area_adddatetime',
        ),
        migrations.AlterField(
            model_name='areacodetype',
            name='area_code_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.codeinareadetail'),
        ),
    ]
