# Generated by Django 4.0.4 on 2022-05-22 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_remove_areacodetype_area_adddatetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationprofile',
            name='station_area_manager',
        ),
        migrations.RemoveField(
            model_name='stationprofile',
            name='station_manager',
        ),
        migrations.AddField(
            model_name='stationprofile',
            name='station_area_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.codeinareadetail'),
        ),
    ]
