# Generated by Django 4.0.4 on 2022-05-22 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_remove_stationprofile_station_area_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlistcodetype',
            name='userList_area_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.codeinareadetail'),
        ),
    ]
