# Generated by Django 4.0.4 on 2022-05-31 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_alter_userlistcodetype_userlist_area_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationprofile',
            old_name='email_notify',
            new_name='debug_mode',
        ),
    ]
