# Generated by Django 4.0.4 on 2022-05-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_historyrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyrequest',
            name='HistoryUserName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
