# Generated by Django 4.0.4 on 2022-05-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_alter_historyrequest_historyusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyrequest',
            name='HistoryUserPosition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historyrequest',
            name='HistoryUserStationID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
